### ISSUE TITLE
Keyboard type dont change

### ISSUE THREAD

**Issue by SuleymanovKamil** [luximetr/AnyFormatKitSwiftUI#1]
How to change keyboard type to numberPad?
.keyboardType(.numberPad) not working

**Comment by luximetr** [comment]
Yes, looks like a bug. I will fix it in a nearest future. If you already have a fix, just create a pull request.

**Comment by SuleymanovKamil** [comment]
I use Introspect and i fixed this issue like this:
 .introspectTextField{ textField in
                    textField.keyboardType = UIKeyboardType.numberPad
                }

**Comment by SuleymanovKamil** [comment]
And its seem you forget to add  platforms in Package.swift

**Comment by luximetr** [comment]
Added, please check.

**Comment by SuleymanovKamil** [comment]
Works good. Thanks
